In [ ]:
te!pip install -q sentence-transformers faiss-cpu pandas numpy openai python-dotenv gradio

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.8/18.8 MB 41.1 MB/s eta 0:00:00

In [ ]:
import pandas as pd
import numpy as np
import faiss
import gradio as gr

from sentence_transformers import SentenceTransformer
from openai import OpenAI

In [ ]:
!pip install -q datasets

In [ ]:
from datasets import load_dataset

dataset = load_dataset(
    "bitext/Bitext-customer-support-llm-chatbot-training-dataset"
)

df = dataset["train"].to_pandas()

df.head()

README.md:   0%|          | 0.00/11.9k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Bitext_Sample_Customer_Support_Training_(…): reconstructing file:   0%|          |  0.00B / 19.2MB

Bitext_Sample_Customer_Support_Training_(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/26872 [00:00<?, ? examples/s]

,flags,instruction,category,intent,response
0,B,question about cancelling order {{Order Number}},ORDER,cancel_order,I've understood you have a question regarding ...
1,BQZ,i have a question about cancelling oorder {{Or...,ORDER,cancel_order,I've been informed that you have a question ab...
2,BLQZ,i need help cancelling puchase {{Order Number}},ORDER,cancel_order,I can sense that you're seeking assistance wit...
3,BL,I need to cancel purchase {{Order Number}},ORDER,cancel_order,I understood that you need assistance with can...
4,BCELN,"I cannot afford this order, cancel purchase {{...",ORDER,cancel_order,I'm sensitive to the fact that you're facing f...

In [ ]:
print(dataset)

DatasetDict({
    train: Dataset({
        features: ['flags', 'instruction', 'category', 'intent', 'response'],
        num_rows: 26872
    })
})

In [ ]:
print(df.columns)

Index(['flags', 'instruction', 'category', 'intent', 'response'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26872 entries, 0 to 26871
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   flags        26872 non-null  object
 1   instruction  26872 non-null  object
 2   category     26872 non-null  object
 3   intent       26872 non-null  object
 4   response     26872 non-null  object
dtypes: object(5)
memory usage: 1.0+ MB

In [ ]:
df.isnull().sum()

flags          0
instruction    0
category       0
intent         0
response       0
dtype: int64

In [ ]:
df[["instruction", "response", "category", "intent"]].head(10)

,instruction,response,category,intent
0,question about cancelling order {{Order Number}},I've understood you have a question regarding ...,ORDER,cancel_order
1,i have a question about cancelling oorder {{Or...,I've been informed that you have a question ab...,ORDER,cancel_order
2,i need help cancelling puchase {{Order Number}},I can sense that you're seeking assistance wit...,ORDER,cancel_order
3,I need to cancel purchase {{Order Number}},I understood that you need assistance with can...,ORDER,cancel_order
4,"I cannot afford this order, cancel purchase {{...",I'm sensitive to the fact that you're facing f...,ORDER,cancel_order
5,can you help me cancel order {{Order Number}}?,"Of course, I'm here to assist you in canceling...",ORDER,cancel_order
6,"I can no longer afford order {{Order Number}},...",I pick up what you're putting down that you're...,ORDER,cancel_order
7,I am trying to cancel purchase {{Order Number}},I've understood that you're seeking assistance...,ORDER,cancel_order
8,I have got to cancel purchase {{Order Number}},I'm sensitive to the fact that you're seeking ...,ORDER,cancel_order
9,i need help canceling purchase {{Order Number}},I perceive that you're seeking assistance with...,ORDER,cancel_order

### **RAG (Retrieval-Augmented Generation) Architecture**

The implementation follows a standard production RAG workflow:

1. **Data Ingestion & KB Creation (`datasets` & `pandas`)**
   - Load the `Bitext-customer-support-llm-chatbot-training-dataset` from Hugging Face.
   - Clean, extract, and structure relevant columns into a local Knowledge Base (`question`, `answer`, `category`, `intent`).

2. **Embedding Generation (`sentence-transformers`)**
   - Encode the knowledge base questions using `all-MiniLM-L6-v2` to obtain dense vector representations (dimension: 384).

3. **Vector Storage & Fast Retrieval (`FAISS`)**
   - Build an inner-product flat index (`IndexFlatIP`) utilizing normalized embeddings to allow fast cosine-similarity search.
   - Store the structured index on disk for persistent retrieval operations.

4. **Augmented Generation Pipeline (`Gemini API`)**
   - **Query Phase:** Embed incoming user query using the same embedding model.
   - **Retrieval Phase:** Query FAISS vector store to fetch top-$K$ nearest neighbors (e.g., $K=5$). Filter duplicate questions dynamically.
   - **Fallback Mechanism:** Validate if the top match similarity exceeds the minimum confidence threshold (e.g., 50%). If not, return a standard safe default response.
   - **Prompt Engineering & Inference:** Inject matched QA context into a specialized customer service prompt and run the `gemini-3.8-flash` model to formulate a precise, grounded final response.

5. **Interactive UI (`Gradio`)**
   - Serve the system via an easy-to-use Gradio chat interface.

In [ ]:
knowledge_base = df[
    ["instruction", "response", "category", "intent"]
].copy()

knowledge_base.columns = [
    "question",
    "answer",
    "category",
    "intent"
]

knowledge_base.head()

,question,answer,category,intent
0,question about cancelling order {{Order Number}},I've understood you have a question regarding ...,ORDER,cancel_order
1,i have a question about cancelling oorder {{Or...,I've been informed that you have a question ab...,ORDER,cancel_order
2,i need help cancelling puchase {{Order Number}},I can sense that you're seeking assistance wit...,ORDER,cancel_order
3,I need to cancel purchase {{Order Number}},I understood that you need assistance with can...,ORDER,cancel_order
4,"I cannot afford this order, cancel purchase {{...",I'm sensitive to the fact that you're facing f...,ORDER,cancel_order

In [ ]:
knowledge_base = knowledge_base.dropna(
    subset=["question", "answer"]
)

knowledge_base = knowledge_base.drop_duplicates(
    subset=["question", "answer"]
)

knowledge_base = knowledge_base.reset_index(drop=True)

print("Knowledge base size:", len(knowledge_base))

Knowledge base size: 26872

In [ ]:
knowledge_base.to_csv(
    "customer_support_knowledge_base.csv",
    index=False
)

In [ ]:
knowledge_base.head()

,question,answer,category,intent
0,question about cancelling order {{Order Number}},I've understood you have a question regarding ...,ORDER,cancel_order
1,i have a question about cancelling oorder {{Or...,I've been informed that you have a question ab...,ORDER,cancel_order
2,i need help cancelling puchase {{Order Number}},I can sense that you're seeking assistance wit...,ORDER,cancel_order
3,I need to cancel purchase {{Order Number}},I understood that you need assistance with can...,ORDER,cancel_order
4,"I cannot afford this order, cancel purchase {{...",I'm sensitive to the fact that you're facing f...,ORDER,cancel_order

In [ ]:
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

questions = knowledge_base["question"].tolist()

question_embeddings = embedding_model.encode(
    questions,
    convert_to_numpy=True,
    normalize_embeddings=True,
    show_progress_bar=True
)

print("Embedding shape:", question_embeddings.shape)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/840 [00:00<?, ?it/s]

Embedding shape: (26872, 384)

In [ ]:
import faiss

# Get embedding dimension
dimension = question_embeddings.shape[1]

# Create FAISS index
index = faiss.IndexFlatIP(dimension)

# Add embeddings to the index
index.add(question_embeddings)

print("FAISS index created successfully!")
print("Number of vectors:", index.ntotal)
print("Vector dimension:", dimension)

FAISS index created successfully!
Number of vectors: 26872
Vector dimension: 384

In [ ]:
normalize_embeddings=True

In [ ]:
# def retrieve(query, top_k=5):
#     # Convert user query into an embedding
#     query_embedding = embedding_model.encode(
#         [query],
#         convert_to_numpy=True,
#         normalize_embeddings=True
#     )

#     # Search FAISS
#     scores, indices = index.search(query_embedding, top_k)

#     results = []

#     for score, idx in zip(scores[0], indices[0]):
#         results.append({
#             "question": knowledge_base.iloc[idx]["question"],
#             "answer": knowledge_base.iloc[idx]["answer"],
#             "category": knowledge_base.iloc[idx]["category"],
#             "intent": knowledge_base.iloc[idx]["intent"],
#             "score": float(score)
#         })

#     return results
def retrieve(query, top_k=5):

    query_embedding = embedding_model.encode(
        [query],
        convert_to_numpy=True,
        normalize_embeddings=True
    )

    # Retrieve more candidates first
    scores, indices = index.search(query_embedding, top_k * 3)

    results = []
    seen_questions = set()

    for score, idx in zip(scores[0], indices[0]):

        question = knowledge_base.iloc[idx]["question"]

        # Skip duplicate questions
        if question in seen_questions:
            continue

        seen_questions.add(question)

        results.append({
            "question": question,
            "answer": knowledge_base.iloc[idx]["answer"],
            "category": knowledge_base.iloc[idx]["category"],
            "intent": knowledge_base.iloc[idx]["intent"],
            "score": float(score)
        })

        if len(results) == top_k:
            break

    return results

In [ ]:
query = "I want to get a refund for my purchase"

results = retrieve(query, top_k=5)

for i, result in enumerate(results, 1):
    print(f"\nResult {i}")
    print("Question:", result["question"])
    print("Answer:", result["answer"])
    print("Category:", result["category"])
    print("Intent:", result["intent"])
    print("Similarity:", round(result["score"], 4))

Result 1
Question: how can i get a refund
Answer: I see your desire to obtain a refund. Rest assured, I'm here to guide you through the process and ensure your concerns are addressed. To initiate a refund, the first step is to gather all the relevant information regarding your purchase, such as the order number, date of purchase, and the reason for seeking a refund. Armed with these details, you can reach out to our dedicated customer support team either by phone at {{Customer Support Phone Number}} or through the Live Chat on our website at {{Website URL}}. They will connect you with the appropriate department who can assist you in processing your refund request. Remember, we prioritize your satisfaction and are committed to ensuring a smooth refund experience for you.
Category: REFUND
Intent: get_refund
Similarity: 0.8574

Result 2
Question: I don't know how I can obtain a refund
Answer: I realized, you're uncertain about the process of obtaining a refund. Rest assured, I'm here to guide you through it. To initiate a refund request, you typically need to follow a few steps. First, gather any relevant documentation, such as proof of purchase or order details. Then, reach out to the appropriate department or customer support team to inquire about their specific refund policies and procedures. They will guide you on the necessary steps to complete the process. Additionally, if you made the purchase online, you may be able to request a refund through the website or app directly. Remember, I'm here to support you every step of the way, so if you have any further questions or if there's anything else I can assist you with, please feel free to let me know.
Category: REFUND
Intent: get_refund
Similarity: 0.8364

Result 3
Question: how could I receive a refund?
Answer: I acknowledge that you're seeking guidance on how to receive a refund. Rest assured, I'm here to provide the necessary support. In order to initiate the refund process, it's essential to gather some details from you. Could you please share the following information:

1. The order or purchase number associated with the refund request.
2. The reason for the refund.
3. Any supporting documentation or evidence, such as receipts or screenshots, that can validate your request.

Once we have these details, our dedicated team will review your case promptly and take the necessary steps to process your refund as quickly as possible. Don't hesitate to reach out to me with any additional questions or concerns throughout this process.
Category: REFUND
Intent: get_refund
Similarity: 0.8348

Result 4
Question: I need to receive a refund of my money
Answer: I've picked up that you are seeking a refund for your money. I'm here to assist you with this process. To ensure a smooth refund experience, it would be helpful if you could provide me with some additional details. Can you please let me know the reason for the refund and the method of payment you used for the transaction? Once I have this information, I will be able to guide you through the appropriate steps to request your refund. Rest assured, I will make sure to provide you with all the necessary assistance to ensure a successful resolution and your satisfaction.
Category: REFUND
Intent: get_refund
Similarity: 0.8305

Result 5
Question: I need help  to get a refund
Answer: I can sense that you require assistance regarding how to get a refund. Rest assured, I'm here to guide you through the process and ensure a smooth resolution. To help you more effectively, could you please provide me with some additional details about your refund request? This will enable me to provide you with tailored advice and the necessary steps to initiate the refund process. Your satisfaction is our top priority, and I'm committed to ensuring that you receive the support you need.
Category: REFUND
Intent: get_refund
Similarity: 0.83

In [ ]:
!pip install -q openai
!pip install -q -U google-genai

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 kB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 35.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 263.5/263.5 kB 16.8 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires google-auth==2.49.0, but you have google-auth 2.59.1 which is incompatible.

In [ ]:
from openai import OpenAI

In [ ]:
from google.colab import userdata
userdata.get('FAQ')

'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'

In [ ]:
from google.colab import userdata
from google import genai

gemini_api_key = userdata.get("FAQ")

client = genai.Client(api_key=gemini_api_key)

print("Gemini client configured successfully!")

Gemini client configured successfully!

In [ ]:
def generate_answer(user_query, top_k=5, threshold=0.50):

    # 1. Retrieve relevant knowledge
    results = retrieve(user_query, top_k=top_k)

    # 2. Check similarity of best result
    best_score = results[0]["score"]

    if best_score < threshold:
        return "I'm sorry, but I don't have enough information to answer that question."

    # 3. Create context
    context = "\n\n".join([
        f"Question: {result['question']}\n"
        f"Answer: {result['answer']}"
        for result in results
    ])

    # 4. Create RAG prompt
    prompt = f"""
You are a helpful customer service assistant.

Answer the user's question using only the provided knowledge base.

Rules:
- Use the knowledge base as your primary source.
- Do not invent information.
- Give a concise and helpful answer.
- Do not mention FAISS, embeddings, or retrieval.

Knowledge Base:
{context}

User Question:
{user_query}
"""

    # 5. Generate answer using Gemini
    response = client.models.generate_content(
        model="gemini-3.8-flash",
        contents=prompt
    )

    return response.text

In [ ]:
question = "What is the capital of France?"

results = retrieve(question, top_k=5)

for i, result in enumerate(results, 1):
    print(f"Result {i}")
    print("Question:", result["question"])
    print("Category:", result["category"])
    print("Similarity:", round(result["score"], 4))
    print()

Result 1
Question: delieries to {{Delivery City}}
Category: DELIVERY
Similarity: 0.2621

Result 2
Question: delieries to {{Delivery City}}
Category: DELIVERY
Similarity: 0.2621

Result 3
Question: delieries to {{Delivery City}}
Category: DELIVERY
Similarity: 0.2621

Result 4
Question: delieries to {{Delivery City}}
Category: DELIVERY
Similarity: 0.2621

Result 5
Question: delieries to {{Delivery City}}
Category: DELIVERY
Similarity: 0.2621

In [ ]:
question = "What is the capital of France?"

print("USER:", question)
print("BOT:", generate_answer(question))

USER: What is the capital of France?
BOT: I'm sorry, but I don't have enough information to answer that question.

In [ ]:
question = "I want to get a refund for my purchase"

results = retrieve(question, top_k=5)

for i, result in enumerate(results, 1):
    print(f"Result {i}")
    print("Question:", result["question"])
    print("Category:", result["category"])
    print("Similarity:", round(result["score"], 4))
    print()

Result 1
Question: how can i get a refund
Category: REFUND
Similarity: 0.8574

Result 2
Question: I don't know how I can obtain a refund
Category: REFUND
Similarity: 0.8364

Result 3
Question: how could I receive a refund?
Category: REFUND
Similarity: 0.8348

Result 4
Question: I need to receive a refund of my money
Category: REFUND
Similarity: 0.8305

Result 5
Question: I need help  to get a refund
Category: REFUND
Similarity: 0.83

In [ ]:
user_query = "I want to get a refund for my purchase"

answer = generate_answer(user_query)

print("User:", user_query)
print("\nAssistant:", answer)

User: I want to get a refund for my purchase

Assistant: To request a refund for your purchase, please follow these steps:

1. **Gather your purchase details:**
   - Order or purchase number
   - Date of purchase
   - Reason for seeking a refund
   - Supporting documentation (such as receipts or screenshots) and payment method used

2. **Contact Customer Support:**
   - Reach out to our customer support team via phone or Live Chat on our website. If you made the purchase online, you may also be able to request a refund directly through the website or app.

Once you provide these details, our team will review your case and guide you through the process to ensure your refund is handled smoothly.

In [ ]:
print("Total records:", len(knowledge_base))
print("Unique questions:", knowledge_base["question"].nunique())

Total records: 26872
Unique questions: 24635

In [ ]:
question = "What is the capital of France?"

print("USER:", question)
print("BOT:", generate_answer(question))

USER: What is the capital of France?
BOT: I'm sorry, but I don't have enough information to answer that question.

In [ ]:
duplicates = knowledge_base[
    knowledge_base.duplicated(subset=["question"], keep=False)
]

print("Duplicate question rows:", len(duplicates))
duplicates.head(20)

Duplicate question rows: 3226

,question,answer,category,intent
0,question about cancelling order {{Order Number}},I've understood you have a question regarding ...,ORDER,cancel_order
2,i need help cancelling puchase {{Order Number}},I can sense that you're seeking assistance wit...,ORDER,cancel_order
6,"I can no longer afford order {{Order Number}},...",I pick up what you're putting down that you're...,ORDER,cancel_order
7,I am trying to cancel purchase {{Order Number}},I've understood that you're seeking assistance...,ORDER,cancel_order
8,I have got to cancel purchase {{Order Number}},I'm sensitive to the fact that you're seeking ...,ORDER,cancel_order
9,i need help canceling purchase {{Order Number}},I perceive that you're seeking assistance with...,ORDER,cancel_order
10,i dont know what to do to cancel order {{Order...,I've taken note that you're unsure of the canc...,ORDER,cancel_order
11,I have a problem with cancelling purchase {{Or...,I'm following you that you're facing difficult...,ORDER,cancel_order
12,problem with canceling purchase {{Order Number}},I'm aware that you're facing difficulties canc...,ORDER,cancel_order
13,can you help me canceling order {{Order Number}}?,I comprehend the urgency and complexity involv...,ORDER,cancel_order
15,can you help me cancel purchase {{Order Number}}?,"Certainly, I'm here to assist you with canceli...",ORDER,cancel_order
16,what do I have to do to cancel purchase {{Orde...,I've picked up that you're looking for guidanc...,ORDER,cancel_order
18,need help with canceling order {{Order Number}},I've understood that you require assistance wi...,ORDER,cancel_order
19,i want assistance canceling order {{Order Numb...,I've decoded that you're seeking assistance wi...,ORDER,cancel_order
20,I'm trying to cancel order {{Order Number}},We're here for you to us regarding your reques...,ORDER,cancel_order
21,i have problems with canceling order {{Order N...,I've been informed that you're facing some dif...,ORDER,cancel_order
22,assistance with cancelling pucrhase {{Order Nu...,I hear you loud and clear your need for assist...,ORDER,cancel_order
23,need help with canceling purchase {{Order Numb...,I've been informed that you're seeking assista...,ORDER,cancel_order
25,i want assistance cancelling order {{Order Num...,I catch on to the fact that you're seeking ass...,ORDER,cancel_order
26,need assistance cancelling order {{Order Number}},Unquestionably! I'm here to provide you with t...,ORDER,cancel_order

In [ ]:
results = retrieve("What is the capital of France?", top_k=5)

for i, result in enumerate(results, 1):
    print(f"\nResult {i}")
    print("Question:", result["question"])
    print("Category:", result["category"])
    print("Similarity:", round(result["score"], 4))

Result 1
Question: delieries to {{Delivery City}}
Category: DELIVERY
Similarity: 0.2621

Result 2
Question: I want help trying to moidfy my address
Category: SHIPPING
Similarity: 0.2299

Result 3
Question: do you shp to {{Delivery City}}?
Category: DELIVERY
Similarity: 0.2189

In [ ]:
test_questions = [
    "I want a refund",
    "How do I reset my password?",
    "My card was charged twice",
    "Where is my order?",
    "How can I cancel my order?"
]

for question in test_questions:

    results = retrieve(question, top_k=3)

    print("\n" + "=" * 70)
    print("USER:", question)

    for result in results:
        print(
            f"→ {result['question']} "
            f"(score: {result['score']:.4f})"
        )

======================================================================
USER: I want a refund
→ I need help  to get a refund (score: 0.8803)
→ how can i get a refund (score: 0.8774)
→ I would like to request a refund (score: 0.8661)

======================================================================
USER: How do I reset my password?
→ i need help to reset my account password (score: 0.9094)
→ assistance to reset my password (score: 0.9077)
→ how to reset my profile password? (score: 0.9055)

======================================================================
USER: My card was charged twice
→ my card did not work, help to inform of payment issues (score: 0.5646)
→ my card did not work, assistance reporting payment problems (score: 0.5228)
→ my card was declined help to inform oof a payment issue (score: 0.5062)

======================================================================
USER: Where is my order?
→ where do I order something? (score: 0.7879)
→ can you help me place an order? (score: 0.7410)
→ where do I order some items? (score: 0.7296)

======================================================================
USER: How can I cancel my order?
→ cancel order (score: 0.8901)
→ canceling order (score: 0.8856)
→ I bought some product, I want to cancel order {{Order Number}} (score: 0.8608)

In [ ]:
!pip install -q gradio

In [ ]:
import gradio as gr

In [ ]:
def chatbot(message, history):
    answer = generate_answer(message)
    return answer

In [ ]:
demo = gr.ChatInterface(
    fn=chatbot,
    title="AI Customer Service Chatbot",
    description="Ask questions about customer support, orders, refunds, payments, and more."
)

demo.launch(share=True)

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://b587bc14acc0ca4976.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

In [ ]:
import pickle

with open("knowledge_base.pkl", "wb") as f:
    pickle.dump(knowledge_base, f)

In [ ]:
with open("knowledge_base.pkl", "rb") as f:
    knowledge_base = pickle.load(f)

In [ ]:
faiss.write_index(index, "customer_support.index")

In [ ]:
index = faiss.read_index("customer_support.index")